import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Layout from '@/components/Layout'
import Slide from '@/components/Slide'
import images from './api/images'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aux Cash for Cars Sydney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <div className={styles.description}>
        </div>
        <Slide images={images}/>
      </main>
    </>
  )
}
