import Head from 'next/head'
import ImageSlider from '@/components/ImageSlider'
import images from './api/images'
import HowWeWorks from '@/components/HowWeWorks'
import AboutCompany from '@/components/AboutCompany'
import CompanyValues from '@/components/CompanyValues'

export default function Home() {
  return (
    <>
      <Head>
        <title>Aux Cash for Cars Sydney</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <ImageSlider images={images}/>
        <HowWeWorks />
        <AboutCompany />
        <CompanyValues />
      </main>
    </>
  )
}
